apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  labels:
    app: playground
spec:
  replicas: 3
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground-container
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: playground-service
  labels:
    app: playground
spec:
  selector:
    app: playground
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  type: ClusterIP
